language: java
sudo: false # faster builds

jdk:
  - openjdk8

branches:
  only:
    - develop
    - feature/*
    - hotfix/*
    - bugfix/*
    - release/*
    - support/*

after_success:
  bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - chanjarster@gmail.com
    - jianbing.cao@supwisdom.com
